import EventType from '../../types/data/EventType';
import Person from '../../types/data/Person';
import Organisation from '../../types/data/Organisation';
import InvalidReason from '../../types/data/InvalidReason';
import InvalidDocument from '../../types/data/InvalidDocument';
import AccountinSystemItem from '../../types/data/AccountinSystemItem';

export const FETCH_PERSONS = 'FETCH_PERSONS';
export const FETCH_PERSONS_ERROR = 'FETCH_PERSONS_ERROR';
export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
export const SET_RB_PERSONS = 'SET_RB_PERSONS';

export const FETCH_EVENT_TYPES = 'FETCH_EVENT_TYPES';
export const FETCH_EVENT_TYPES_ERROR = 'FETCH_EVENT_TYPES_ERROR';
export const FETCH_EVENT_TYPES_SUCCESS = 'FETCH_EVENT_TYPES_SUCCESS';
export const SET_RB_EVENT_TYPES = 'SET_RB_EVENT_TYPES';

export const FETCH_INVALID_REASONS = 'FETCH_INVALID_REASONS';
export const FETCH_INVALID_REASONS_ERROR = 'FETCH_INVALID_REASONS_ERROR';
export const FETCH_INVALID_REASONS_SUCCESS = 'FETCH_INVALID_REASONS_SUCCESS';
export const SET_RB_INVALID_REASONS = 'SET_RB_INVALID_REASONS';

export const FETCH_ORGANISATIONS = 'FETCH_ORGANISATIONS';
export const FETCH_ORGANISATIONS_ERROR = 'FETCH_ORGANISATIONS_ERROR';
export const FETCH_ORGANISATIONS_SUCCESS = 'FETCH_ORGANISATIONS_SUCCESS';
export const SET_RB_ORGANISATIONS = 'SET_RB_ORGANISATIONS';

export const FETCH_INVALID_DOCUMENTS = 'FETCH_INVALID_DOCUMENTS';
export const FETCH_INVALID_DOCUMENTS_ERROR = 'FETCH_INVALID_DOCUMENTS_ERROR';
export const FETCH_INVALID_DOCUMENTS_SUCCESS =
  'FETCH_INVALID_DOCUMENTS_SUCCESS';
export const SET_RB_INVALID_DOCUMENTS = 'SET_RB_INVALID_DOCUMENTS';

export const FETCH_ACCOUNTING_SYSTEM = 'FETCH_ACCOUNTING_SYSTEM';
export const FETCH_ACCOUNTING_SYSTEM_ERROR = 'FETCH_ACCOUNTING_SYSTEM_ERROR';
export const FETCH_ACCOUNTING_SYSTEM_SUCCESS =
  'FETCH_ACCOUNTING_SYSTEM_SUCCESS';
export const SET_RB_ACCOUNTING_SYSTEM = 'SET_RB_ACCOUNTING_SYSTEM';

export interface FETCH_PERSONS {
  type: typeof FETCH_PERSONS;
}

export interface FETCH_PERSONS_ERROR {
  type: typeof FETCH_PERSONS_ERROR;
}

export interface FETCH_PERSONS_SUCCESS {
  type: typeof FETCH_PERSONS_SUCCESS;
}

export interface FETCH_EVENT_TYPES {
  type: typeof FETCH_EVENT_TYPES;
}

export interface FETCH_EVENT_TYPES_ERROR {
  type: typeof FETCH_EVENT_TYPES_ERROR;
}

export interface FETCH_EVENT_TYPES_SUCCESS {
  type: typeof FETCH_EVENT_TYPES_SUCCESS;
}

export interface SET_RB_PERSONS {
  type: typeof SET_RB_PERSONS;
  payload: Person[];
}

export interface SET_RB_EVENT_TYPES {
  type: typeof SET_RB_EVENT_TYPES;
  payload: EventType[];
}

export interface FETCH_INVALID_REASONS {
  type: typeof FETCH_INVALID_REASONS;
}

export interface FETCH_INVALID_REASONS_ERROR {
  type: typeof FETCH_INVALID_REASONS_ERROR;
}

export interface FETCH_INVALID_REASONS_SUCCESS {
  type: typeof FETCH_INVALID_REASONS;
}

export interface SET_RB_INVALID_REASONS {
  type: typeof SET_RB_INVALID_REASONS;
  payload: InvalidReason[];
}

export interface FETCH_ORGANISATIONS {
  type: typeof FETCH_ORGANISATIONS;
}

export interface FETCH_ORGANISATIONS_ERROR {
  type: typeof FETCH_ORGANISATIONS_ERROR;
}

export interface FETCH_ORGANISATIONS_SUCCESS {
  type: typeof FETCH_ORGANISATIONS_SUCCESS;
}

export interface SET_RB_ORGANISATIONS {
  type: typeof SET_RB_ORGANISATIONS;
  payload: Organisation[];
}

export interface FETCH_INVALID_DOCUMENTS {
  type: typeof FETCH_INVALID_DOCUMENTS;
}

export interface FETCH_INVALID_DOCUMENTS_ERROR {
  type: typeof FETCH_INVALID_DOCUMENTS_ERROR;
}

export interface FETCH_INVALID_DOCUMENTS_SUCCESS {
  type: typeof FETCH_INVALID_DOCUMENTS_SUCCESS;
}

export interface SET_RB_INVALID_DOCUMENTS {
  type: typeof SET_RB_INVALID_DOCUMENTS;
  payload: InvalidDocument[];
}

export interface FETCH_ACCOUNTING_SYSTEM {
  type: typeof FETCH_ACCOUNTING_SYSTEM;
}

export interface FETCH_ACCOUNTING_SYSTEM_ERROR {
  type: typeof FETCH_ACCOUNTING_SYSTEM_ERROR;
}

export interface FETCH_ACCOUNTING_SYSTEM_SUCCESS {
  type: typeof FETCH_ACCOUNTING_SYSTEM_SUCCESS;
}

export interface SET_RB_ACCOUNTING_SYSTEM {
  type: typeof SET_RB_ACCOUNTING_SYSTEM;
  payload: AccountinSystemItem[];
}

export type RbActionsType =
  | FETCH_PERSONS
  | FETCH_PERSONS_ERROR
  | FETCH_PERSONS_SUCCESS
  | FETCH_EVENT_TYPES
  | FETCH_EVENT_TYPES_ERROR
  | SET_RB_PERSONS
  | SET_RB_EVENT_TYPES
  | FETCH_EVENT_TYPES_SUCCESS
  | FETCH_INVALID_REASONS
  | FETCH_INVALID_REASONS_ERROR
  | FETCH_INVALID_REASONS_SUCCESS
  | SET_RB_INVALID_REASONS
  | FETCH_ORGANISATIONS
  | FETCH_ORGANISATIONS_ERROR
  | FETCH_ORGANISATIONS_SUCCESS
  | SET_RB_ORGANISATIONS
  | FETCH_INVALID_DOCUMENTS
  | FETCH_INVALID_DOCUMENTS_ERROR
  | FETCH_INVALID_DOCUMENTS_SUCCESS
  | SET_RB_INVALID_DOCUMENTS
  | FETCH_ACCOUNTING_SYSTEM
  | FETCH_ACCOUNTING_SYSTEM_ERROR
  | FETCH_ACCOUNTING_SYSTEM_SUCCESS
  | SET_RB_ACCOUNTING_SYSTEM;
